### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by anubhav-cs**
The commit resolves a bug in the processing of goal condition composed of a single negative atom in the FD to LAPKT translator.

### CODE REVIEW

**Comment by anubhav-cs** [comment]
I created this PR after the bugfix deadline of IPC 23  

Just wanted to make a note for anyone reading this in the future that this bug impacts all of IPC23 Labyrinth and a few instances of Recharging Robots

**Comment by FlorianPommerening** [comment]
I changed the target of this PR to the `latest` branch (the `ipc2023-classical` branch should remain in the state it ran in the competition). For some reason this closed the PR. I'll try to fix it on my end.

**Comment by FlorianPommerening** [comment]
Sorry, I cannot reopen the pull request. Could you send it again, targeting the branch `latest`?

**Comment by anubhav-cs** [comment]
Sorry for the delay. This somehow got past my radar. I have created a new PR targeting `latest` branch.

**Comment by FlorianPommerening** [comment]
Thanks, I merged it. Sorry again for the confusion with the branches.

**Pull request closed without merging**
